name: Twitter to Mastodon Bot

on:
  workflow_dispatch: # Manuelle Ausführung

jobs:
  run-twitter-to-mastodon:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Firefox and GeckoDriver (Alpine)
        run: |
          apk update
          apk add --no-cache firefox
          apk add --no-cache wget
          wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-linux64.tar.gz
          tar -xzf geckodriver-linux64.tar.gz
          mv geckodriver /usr/local/bin/
          chmod +x /usr/local/bin/geckodriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Twitter to Mastodon Script
        env:
          MASTODON_API_URL: ${{ secrets.MASTODON_API_URL }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          TWITTER_URL: ${{ secrets.TWITTER_URL }}
          HASHTAGS: ${{ secrets.HASHTAGS }}
        run: python twitter2mastodon.py
