name: Twitter to Mastodon Bot

on:
  schedule:
    - cron: '0 6 * * *'    # Einmal täglich um 06:00 Uhr
    - cron: '0 13-22 * * *' # Stündlich von 13:00 bis 22:00 Uhr
  workflow_dispatch:        # Manuelle Ausführung

jobs:
  run-twitter-to-mastodon:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Firefox and GeckoDriver
        run: |
          brew install --cask firefox
          brew install geckodriver
          echo "Firefox-Version:"
          firefox --version
          echo "GeckoDriver-Version:"
          geckodriver --version
          echo "GeckoDriver-Pfad:"
          which geckodriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Twitter to Mastodon Script
        env:
          MASTODON_API_URL: ${{ secrets.MASTODON_API_URL }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          TWITTER_URL: ${{ secrets.TWITTER_URL }}
          HASHTAGS: ${{ secrets.HASHTAGS }}
        run: |
          echo "Starting the script..."
          python twitter2mastodon.py || echo "Script execution failed. Check logs above for details."
